### ISSUE TITLE
Hosting a console application inside IIS

### ISSUE THREAD

**Issue by xavierzwirtz** [richardadalton/EloRateApi#1]
I saw on your blog that you were having trouble hosting a Suave server on Azure. I have not hosted Suave on Azure, but I have hosted it in IIS using `HttpPlatformHandler`. This is the web.config that I used:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="server.exe" 
                  arguments="--port %HTTP_PLATFORM_PORT%"
                  stdoutLogEnabled="true" 
                  stdoutLogFile=".\log.txt">
    </httpPlatform>
  </system.webServer>
</configuration>
```

You would need to create a console application that started a suave server specified by the `--port` argument.

**Comment by richardadalton** [comment]
Hey thanks for that.

The hosting on Azure also uses HttpPlatformHandler. I don't know if
that'll work, but
I'll give it a look.

I also need to try hosting it in a cloud service.

-Richard

**Comment by richardadalton** [comment]
Looks like exactly the approach @isaac_abraham used last night to get it working on Azure.
https://t.co/W4trS1zalM
